// Autogenerated file run "yarn mk-images"

export const imageRepository = 
{
  "landing:landingPage.poster": "http://localhost/_assets_server/images/cerro/cerro-panoramic-dron.jpg",
  "personnel:profile.pepe": "/_assets_server/images/personnel/pepe.jpg"
}

export type iKeyNames = 
  'landing:landingPage.poster'
| 'personnel:profile.pepe'
