// Autogenerated file run "yarn mk-locales"

export const validTranslationKeys = {
    en: {
        'common:menu.home': 'mecuate',
        'common:menu.mecuate': 'Mecuate',
        'common:menu.academy': 'Academy',
        'common:menu.services': 'Services',
        'common:menu.docuweb': 'DocuWeb',
        'common:menu.projects': 'Projects',
        'common:menu.publications': 'Publications',
        'common:menu.contact': 'Contact',
        'common:menu.previousWorkShops': 'Previous',
        'common:menu.nextWorkShops': 'Comming next',
        'common:menu.currentWorkShops': 'Current',
        'common:menu.production': 'Production',
        'common:menu.docuweb_2021': 'Ambiental Docuweb (2021)',
        'common:menu.project_00': 'Meztitlan',
        'common:menu.project_01': 'Christmas flower',
        'common:menu.project_02': 'Stars Hill',
        'common:menu.project_03': 'Untitled (Noplea)',
        'common:menu.project_04': 'Cultivarte',
        'common:menu.project_05': 'Flora of the Stars Hill',
        'common:menu.academic': 'Academic publications',
        'common:menu.blogs': 'Other media',
    },
    es: {
        'academy:frontPage.title': 'Bienvenido a la Academia mecuate astrophytum',
        'academy:frontPage.description': 'this academy is made for all peoples from anywhrer in the universe.',
        'academy:workShopPage.groupName': 'Nombre de Grupo',
        'academy:workShopPage.groupType.solid': 'Grupo sólido',
        'academy:workShopPage.groupType.stable': 'Grupo fijo',
        'academy:workShopPage.groupType.morph': 'Grupo Anomórfico',
        'common:menu.home': 'mecuate',
        'common:menu.mecuate': 'Mecuate',
        'common:menu.academy': 'Academia',
        'common:menu.services': 'Servicios',
        'common:menu.docuweb': 'DocuWeb',
        'common:menu.projects': 'Proyectos',
        'common:menu.publications': 'Publicaciones',
        'common:menu.contact': 'Contacto',
        'common:menu.previousWorkShops': 'Previos',
        'common:menu.nextWorkShops': 'Proximos',
        'common:menu.currentWorkShops': 'Actuales',
        'common:menu.production': 'Producción',
        'common:menu.docuweb_2021': 'Docuweb ambiental (2021)',
        'common:menu.project_00': 'Meztitlan',
        'common:menu.project_01': 'Nochebuena',
        'common:menu.project_02': 'Cerro de la Estrella',
        'common:menu.project_03': 'Sin Titulo (Noples)',
        'common:menu.project_04': 'cultivarte',
        'common:menu.project_05': 'La flora del cerro de la estrella',
        'common:menu.academic': 'Publicaciones academicas',
        'common:menu.blogs': 'Otros medios',
    },
    ko: {
        'common:menu.home': '메큐에이트',
        'common:menu.mecuate': '메큐에이트',
        'common:menu.academy': '학원',
        'common:menu.services': '서비스',
        'common:menu.docuweb': '도큐웹',
        'common:menu.projects': '프로젝트',
        'common:menu.publications': '게시',
        'common:menu.contact': '접촉',
        'common:menu.previousWorkShops': '이전의',
        'common:menu.nextWorkShops': '다음에 컴밍',
        'common:menu.currentWorkShops': '전류',
        'common:menu.production': '생산',
        'common:menu.docuweb_2021': 'Ambiental Docuweb (2021)',
        'common:menu.project_00': '메즈티틀란',
        'common:menu.project_01': '크리스마스 꽃',
        'common:menu.project_02': '스타 힐',
        'common:menu.project_03': '제목 없음 (Noplea)',
        'common:menu.project_04': '재배',
        'common:menu.project_05': '별 언덕의 식물상',
        'common:menu.academic': '별 언덕의 식물상',
        'common:menu.blogs': '학술 간행물 다른 미디어',
    },
}

export type iKeyTranslations =
    | 'common:menu.home'
    | 'common:menu.mecuate'
    | 'common:menu.academy'
    | 'common:menu.services'
    | 'common:menu.docuweb'
    | 'common:menu.projects'
    | 'common:menu.publications'
    | 'common:menu.contact'
    | 'common:menu.previousWorkShops'
    | 'common:menu.nextWorkShops'
    | 'common:menu.currentWorkShops'
    | 'common:menu.production'
    | 'common:menu.docuweb_2021'
    | 'common:menu.project_00'
    | 'common:menu.project_01'
    | 'common:menu.project_02'
    | 'common:menu.project_03'
    | 'common:menu.project_04'
    | 'common:menu.project_05'
    | 'common:menu.academic'
    | 'common:menu.blogs'
    | 'academy:frontPage.title'
    | 'academy:frontPage.description'
    | 'academy:workShopPage.groupName'
    | 'academy:workShopPage.groupType.solid'
    | 'academy:workShopPage.groupType.stable'
    | 'academy:workShopPage.groupType.morph'

export type LangKeys = keyof typeof validTranslationKeys
